services:
  demo_bdd:
    container_name: demo_mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: TOOR
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    profiles: [local, prod, dev]

  demo_adminer:
    container_name: demo_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles: [local, dev]
