services:
  
  bdd-build:
    container_name: bdd_build
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bddname
      MYSQL_USER: roger
      MYSQL_PASSWORD: regor
  
  backend-build:
    container_name: backend_build
    restart: always
    build: .
    environment:
      BDD_HOST: bdd-build
    ports:
      - 23000:23000
