name: Test FrontEnd

on:
  workflow_call

jobs:
  testFrontEnd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Builded Backend Docker
        working-directory: backend
        run: |
          docker compose -f docker-compose-build.yml up -d
          docker ps -a

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Test Backend Container
        if: success()
        run: curl http://127.0.0.1:23000

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: frontend

      - name: Intall Frontend Packages
        run: npm i

      - name: Start E2E Test
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: frontend
          start: npm run dev
				
      # Upload Cypress Test Result
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          retention-days: 1

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          retention-days: 1

      - name: Clean Builded Backend Docker
        working-directory: backend
        run: docker compose -f docker-compose-build.yml down