name: Intregation

on:
    push:
        branches: ["main"]

jobs:
    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        services:
            mariadb:
                image: mariadb:latest
                env:
                    MARIADB_ROOT_PASSWORD: toor
                    MARIADB_DATABASE: test
                    MARIADB_USER: test
                    MARIADB_PASSWORD: test
                ports:
                    - 3306:3306
                options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
  
        env:
            BDD_HOST: 127.0.0.1
            BDD_NAME: test
            BDD_USER: test
            BDD_PASS: test

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Check Database Connection
              run: |
                sudo apt-get install -y mysql-client
                mysql --host 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES"   
            
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Install Dependencies
              run: npm i

            - name: Init Database
              run: npm run initbdd
            - name: Add Admin Test User
              run: |
                mysql -u root -ptoor --host 127.0.0.1 --port 3306 --database test < ./test/insert_test_user.sql

            # - name: Run Main Router Test
            #   run: npm run test:file main_route

            - name: Run all test and coverage
              run: npm run test:cov
              
            - name: Upload Coverage Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: coverage-repport
                path: ./coverage
                retention-days: 3
            - name: JUST TO SEE
              run: pwd

            - name: SonarQube Quality
              uses: SonarSource/sonarcloud-github-action@v3.1.0
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
